Upload arweave function
nextdotid/kv_server pull request #12
Opened 2023-09-03 12:03 UTC by lyfer233

Added:
1. Using the third package `arweave-rs` connect with the arweave.
2. Added a new field `arweave_id` to the kv_chains table and update the `src/schema.rs` file.
3. Updated two unit tests because add a field.
4. Add a unit test to ensure the connection with arweave and upload function.

Need to improve:
1. Error process.
2. Upload to the arweave document.

2023-09-03 12:58 UTC, nykma requested changes

2023-09-03 12:58 UTC, nykma commented on migrations/2023_08_01-add_arewave_id_to_kv_chains/up.sql
> +ADD arweave_id VARCHAR DEFAULT '';
Will `DEFAULT ''` be conflict with `Option<String>` ? I'm not sure about this.

2023-09-03 12:58 UTC, nykma commented on src/controller/upload.rs
> +        avatar: avatar.unwrap(),
Will `unwrap()` here be paniced?

2023-09-03 12:58 UTC, nykma commented on src/controller/upload.rs
> +    new_kv.arweave_id = match arweave_document.upload_to_arweave().await {
```suggestion
    new_kv.arweave_id = match arweave_document.upload_to_arweave().ok();
```

2023-09-03 12:58 UTC, nykma commented on src/error/mod.rs
> +            Error::ArweaveError(_) => StatusCode::BAD_REQUEST,
Basiclly Arweave upload error is not user's fault, so it should be `5xx`, like `INTERNAL_SERVER_ERROR`

2023-09-03 12:58 UTC, nykma commented on src/model/arweave/mod.rs
> +pub struct KVChainArweaveDocument {
Why creating a new `Model` here?

2023-09-04 16:03 UTC, lyfer233 commented
Current problem:
- `arweave_id` not normally add into response when user post to `/v1/kv`, so I will think how to design and refactor some codes to address this issue.

2023-09-05 08:08 UTC, nykma commented on src/controller/upload.rs
> +    new_kv.arweave_id = arweave_document.upload_to_arweave().await.ok();
Please make this upload procedure a "background job". 
Uploading should not "block" this upload request.

2023-09-08 03:09 UTC, lyfer233 commented
Next plans:
1. fix this problem https://github.com/NextDotID/kv_server/pull/12#issuecomment-1705489400
2. Use thread to run upload job
3. Add more unit test to ensure error process and corner condition.

2023-09-25 07:41 UTC, nykma requested changes
Good enough. Only a small thing to tweak.

2023-09-25 07:41 UTC, nykma commented on src/controller/upload.rs
> +    new_kv.arweave_id = arweave_upload_future.await.unwrap();
It still blocks `json_response` below.

What I mean is, spawning a tokio background job and leave it alone.

2023-10-25 17:12 UTC, nykma reviewed
Good for now. I'll fix some trivial stuff.

2023-10-25 17:12 UTC, nykma approved these changes
Good for now. I'll fix some trivial stuff.

2023-10-25 18:31 UTC, merged